# Variables
DOCKER_COMPOSE = docker-compose
ADMIN_DIR = admin
USER_DIR = users

# Targets
.PHONY: start stop logs status test-users test-admin

test-all: test-admin test-users

start:
	@echo "Starting Docker containers..."
	$(DOCKER_COMPOSE) -f $(ADMIN_DIR)/compose.yaml up -d --build
	sleep 10
	$(DOCKER_COMPOSE) -f $(USER_DIR)/compose.yaml up -d --build

stop:
	@echo "Stopping Docker containers..."
	$(DOCKER_COMPOSE) -f $(ADMIN_DIR)/compose.yaml down
	$(DOCKER_COMPOSE) -f $(USER_DIR)/compose.yaml down

logs:
	@echo "Viewing Docker logs..."
	$(DOCKER_COMPOSE) -f $(ADMIN_DIR)/compose.yaml logs
	$(DOCKER_COMPOSE) -f $(USER_DIR)/compose.yaml logs

status:
	@echo "Viewing Docker logs..."
	$(DOCKER_COMPOSE) -f $(ADMIN_DIR)/compose.yaml ps
	$(DOCKER_COMPOSE) -f $(USER_DIR)/compose.yaml ps

test-users:
	@echo "Running tests on user api..."
	$(DOCKER_COMPOSE) -f $(USER_DIR)/compose.yaml exec api python manage.py test tests

test-admin:
	@echo "Running tests on admin api..."
	$(DOCKER_COMPOSE) -f $(ADMIN_DIR)/compose.yaml exec api python manage.py test tests