version: '3.8'

services:
  
  db:
    image: postgres:14.1-alpine
    env_file:
      - ./.env
    ports:
      - '${DB_PORT}:5432'
    restart: unless-stopped
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: 'users_db'
    volumes:
      - users-db:/var/lib/postgresql/data
    networks:
      - admin-network

  redis:
    image: "redis:alpine"
    container_name: "redis"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - admin-network

  api: &api
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./.env
    ports:
      - '${BACKEND_PORT}:8000'
    volumes:
      - ./app:/app
    restart: always
    depends_on:
      - db
      - redis
    networks:
      - admin-network

volumes:
  users-db:

networks:
  admin-network:
    external: true
    # driver: bridge
    name: admin-network